# Generated by Django 3.0.3 on 2020-02-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default='asd'),
            preserve_default=False,
        ),
    ]
